services:
  grafana:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_PASSWORD=password_password
    volumes:
      - ./provisioning:/etc/grafana/provisioning
